"""pymasondesign: Core para dimensionamento de alvenaria estrutural."""

from __future__ import annotations

from pymasondesign.geometry import (
    Point2D,
    Vector2D,
    BoundingBox,
    Transform2D,
    Polygon,
    Axis,
    AxisRelation,
    AxisIntersectionResult,
    GEOMETRIC_TOLERANCE,
    JUNCTION_TOLERANCE,
    OVERLAP_TOLERANCE,
    DIVISION_GUARD,
    is_zero,
    is_not_zero,
    is_close,
    is_not_close,
    is_greater,
    is_greater_or_equal,
    is_less,
    is_less_or_equal,
    is_positive,
    is_negative,
    is_non_negative,
    is_non_positive,
    is_between,
    is_strictly_between,
    is_within_unit,
    is_at_start,
    is_at_end,
    is_at_vertex,
    is_interior,
)
from pymasondesign.sections import (
    Section,
    SectionProperties,
    RectangularSection,
    PolygonSection,
    CompositeSection,
    SectionComponent,
)
from pymasondesign.mechanics import (
    NormalStressPlane,
    SectionForces,
    StressRegime,
    MechanicsService,
    DEFAULT_TOLERANCE,
)
from pymasondesign.materials import (
    SteelCategory,
    BlockMaterialType,
    StrengthClass,
    BlockStrengthClass,
    CeramicWallType,
    BlockWallType,
    SteelSpecification,
    BlockSpecification,
    MortarSpecification,
    GroutSpecification,
    MasonrySpecification,
    NBR16868TableEntry,
    NBR16868MasonryFactory,
)
from pymasondesign.drafting import (
    OpeningType,
    BondType,
    WallEnd,
    Opening,
    Wall,
    ArrivingWall,
    Junction,
    FloorPlan,
    Story,
    Building,
)
from pymasondesign.common import to_tuple
from pymasondesign.structure import (
    MasonryPanel,
    PanelGroup,
    FloorPlanModel,
    StoryModel,
    BuildingModel,
    MasonryPanelService,
    SegmentRole,
    BracingSegment,
    BracingWall,
    BracingOptions,
    BracingWallService,
)
from pymasondesign.design import (
    FlangeOptions,
    ResistantSegment,
    ResistantSection,
    ResistantSectionService,
    GroutInterval,
    SegmentGroutDemand,
    SectionGroutDemand,
    CompressionDesignOptions,
    CompressionDesignResult,
    CompressionVerificationResult,
    CompressionDesignService,
)

__version__ = "0.1.0"

__all__ = [
    # Geometria pura 2D
    "Point2D",
    "Vector2D",
    "BoundingBox",
    "Transform2D",
    "Polygon",
    "Axis",
    "AxisRelation",
    "AxisIntersectionResult",
    "GEOMETRIC_TOLERANCE",
    "JUNCTION_TOLERANCE",
    "OVERLAP_TOLERANCE",
    "DIVISION_GUARD",
    "is_zero",
    "is_not_zero",
    "is_close",
    "is_not_close",
    "is_greater",
    "is_greater_or_equal",
    "is_less",
    "is_less_or_equal",
    "is_positive",
    "is_negative",
    "is_non_negative",
    "is_non_positive",
    "is_between",
    "is_strictly_between",
    "is_within_unit",
    "is_at_start",
    "is_at_end",
    "is_at_vertex",
    "is_interior",
    # Seções transversais estruturais
    "Section",
    "SectionProperties",
    "RectangularSection",
    "PolygonSection",
    "CompositeSection",
    "SectionComponent",
    # Mecânica e tensões
    "NormalStressPlane",
    "SectionForces",
    "StressRegime",
    "MechanicsService",
    "DEFAULT_TOLERANCE",
    # Materiais estruturais
    "SteelCategory",
    "BlockMaterialType",
    "StrengthClass",
    "BlockStrengthClass",
    "CeramicWallType",
    "BlockWallType",
    "SteelSpecification",
    "BlockSpecification",
    "MortarSpecification",
    "GroutSpecification",
    "MasonrySpecification",
    "NBR16868TableEntry",
    "NBR16868MasonryFactory",
    # Lançamento estrutural (Drafting)
    "OpeningType",
    "BondType",
    "WallEnd",
    "Opening",
    "Wall",
    "ArrivingWall",
    "Junction",
    "FloorPlan",
    "Story",
    "Building",
    # Utilitários e Helpers comuns
    "to_tuple",
    # Elementos estruturais e contraventamento
    "MasonryPanel",
    "PanelGroup",
    "FloorPlanModel",
    "StoryModel",
    "BuildingModel",
    "MasonryPanelService",
    "SegmentRole",
    "BracingSegment",
    "BracingWall",
    "BracingOptions",
    "BracingWallService",
    # Dimensionamento e Verificação (Design)
    "FlangeOptions",
    "ResistantSegment",
    "ResistantSection",
    "ResistantSectionService",
    "GroutInterval",
    "SegmentGroutDemand",
    "SectionGroutDemand",
    "CompressionDesignOptions",
    "CompressionDesignResult",
    "CompressionVerificationResult",
    "CompressionDesignService",
    "__version__",
]
